/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multiplayer.minesweeper.server;

import io.vertx.core.AbstractVerticle;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import multiplayer.minesweeper.game.GamesManager;

public class HttpServer extends AbstractVerticle {
    private final static HttpServer instance = new HttpServer();

    private HttpServer() {}

    private void createNewGame(RoutingContext rc) {
        System.out.println("Received new-game request.");

        int gridWidth = rc.get("gridWidth", 4);
        int gridHeight = rc.get("gridHeight", 4);
        float minesPercentage = rc.get("minesPercentage", 0.4f);
//        int numConnectedPlayers = rc.get("numConnectedPlayers");
//        int numPlayers = rc.get("numPlayers");

        String gameId = GamesManager.getInstance().newGame(gridWidth, gridHeight, minesPercentage);

        System.out.println("Created new-game, created Socketio room." + gameId);

        rc.response()
                .putHeader("content-type",
                        "application/json; charset=utf-8")
                .end(gameId);
    }
    @Override
    public void start() {
        Router router = Router.router(vertx);

        router.post("/new-game").handler(this::createNewGame);

        vertx.createHttpServer()
                .requestHandler(router)
                .listen(8003)
                .onSuccess(server ->
                        System.out.println(
                                "HTTP server started on port " + server.actualPort()
                        )
                );
    }

    public static HttpServer getInstance() {
        return instance;
    }
}