/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multiplayer.minesweeper.server;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.json.Json;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import multiplayer.minesweeper.game.GameManager;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class HttpServer extends AbstractVerticle {
    private final Map<String, GameManager> activeGames = new HashMap<>();

    private void createNewGame(RoutingContext rc) {
        int gridWidth = rc.get("width", 4);
        int gridHeight = rc.get("height", 4);

        String gameId = UUID.randomUUID().toString();
        GameManager newInstance = new GameManager(gridWidth, gridHeight);
        activeGames.put(gameId, newInstance);
        rc.response()
                .putHeader("content-type",
                        "application/json; charset=utf-8")
                .end(Json.encodePrettily(gameId));
    }

    @Override
    public void start() {
        // Create a Router
        Router router = Router.router(vertx);

        router.post("/new-game").handler(this::createNewGame);

        vertx.createHttpServer()
                .requestHandler(router)
                .listen(8888)
                .onSuccess(server ->
                        System.out.println(
                                "HTTP server started on port " + server.actualPort()
                        )
                );
    }
}