stages:
  - triggers
  - deploy

trigger:frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - frontend/*
        - .gitlab-ci.yml

trigger:session:
  stage: triggers
  trigger:
    include: server-session/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - server_session/*
        - .gitlab-ci.yml

trigger:game:
  stage: triggers
  trigger:
    include: server-game/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - server_game/*
        - .gitlab-ci.yml

deploy-prod:
  stage: deploy
  needs: ["trigger:frontend", "trigger:session", "trigger:game"]
  script:
    - echo "Successful delivery to master branch"
  rules:
      - if: '$CI_COMMIT_BRANCH == "master"'
#   environment: production