stages:
  - triggers

trigger:frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci.yml
  rules:
    - changes:
        - frontend/*

trigger:session:
  stage: triggers
  trigger:
    include: server_session/.gitlab-ci.yml
  rules:
    - changes:
        - server_session/*

trigger:game:
  stage: triggers
  trigger:
    include: server_game/.gitlab-ci.yml
  rules:
    - changes:
        - server_game/*

# deploy-prod:
#   stage: deploy
#   needs: ["trigger:frontend", "trigger:session", "trigger:game"]
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production