build:frontend:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
  
build:session:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

build:game:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:session:
  stage: test
  needs: ["build:session"]
  script:
    - echo "This job tests something"

test:game:
  stage: test
  needs: ["build:game"]
  script:
    - echo "This job tests something, but takes more time than test:job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test:job1"
    - sleep 20

deploy-prod:
  stage: deploy
  needs: ["build:frontend", "test:session", "test:game"]
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production