stages:
  - triggers
  - deploy

trigger:frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  # rules:
  #   - changes:
  #       - frontend/*

trigger:session:
  stage: triggers
  trigger:
    include: server-session/.gitlab-ci.yml
    strategy: depend
  # rules:
  #   - changes:
  #       - server_session/*

trigger:game:
  stage: triggers
  trigger:
    include: server-game/.gitlab-ci.yml
    strategy: depend
  # rules:
  #   - changes:
  #       - server_game/*

deploy-prod:
  stage: deploy
  needs: ["trigger:frontend", "trigger:session", "trigger:game"]
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production