version: "3.9"

services:
  frontend:
    container_name: mmfrontend
    image: mmfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mmnetwork

  session:
    container_name: mmsession
    image: mmsession
    build:
      context: ./server-session
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      - mmnetwork

  game:
    container_name: mmgame
    image: mmgame
    build:
      context: ./server-game
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
      - "8004:8004"
    networks:
      - mmnetwork

networks:
  mmnetwork:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "brmmnetwork"
