version: "3.9"

services:
  frontend:
    container_name: mmfrontend
    hostname: mmfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - compose-mmnetwork

  session:
    container_name: mmsession
    hostname: mmsession
    build:
      context: ./server-session
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      - compose-mmnetwork

  game:
    container_name: mmgame
    hostname: mmgame
    build:
      context: ./server-game
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
      - "8004:8004"
    networks:
      - compose-mmnetwork

networks:
  compose-mmnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
          gateway: 172.19.1.1
          ip_range: 172.19.1.2/20
