version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      compose-mmnetwork:
        ipv4_address: 172.18.0.10

  session:
    build:
      context: ./server-session
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      compose-mmnetwork:
        ipv4_address: 172.18.0.11

  game:
    build:
      context: ./server-game
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
      - "8004:8004"
    networks:
      compose-mmnetwork:
        ipv4_address: 172.18.0.12

networks:
  compose-mmnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
          ip_range: 172.18.0.2/20
