/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multiplayer.minesweeper.http.server;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpMethod;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.CorsHandler;
import multiplayer.minesweeper.sessions.Session;
import multiplayer.minesweeper.sessions.SessionsManager;
import multiplayer.minesweeper.websocket.SocketServer;

import java.util.UUID;

public class HTTPServer extends AbstractVerticle {
    private static HTTPServer instance = new HTTPServer();
    private Router router;
    private int port;
    private HTTPServer() {};

    public static HTTPServer get() {
        return instance;
    }

    public void initialize(Vertx vertx, int port ) {
        this.port = port;
        // Create a Router
        router = Router.router(vertx);
        // Allow specific CORS request origins
        router.route().handler(
                CorsHandler.create(".*.")
                        .allowedMethod(HttpMethod.GET)
                        .allowedMethod(HttpMethod.POST));

        router.post("/new-session").handler(this::createNewSession);
        vertx.deployVerticle(this);
    }

    private void createNewSession(RoutingContext rc) {
        rc.request().bodyHandler(bodyHandler -> {
            final JsonObject body = bodyHandler.toJsonObject();
            System.out.println("[HTTP Server] - Received new-session request. Body: " + body);

            try {
                String sessionName = body.getString("name");
                String mode = body.getString("mode");
                int numPlayers = body.getInteger("numPlayers");
                int gridWidth = body.getInteger("gridWidth");
                int gridHeight = body.getInteger("gridHeight");

                if (sessionName.isBlank() || mode.isBlank()) {
                    throw new IllegalArgumentException();
                }

                String roomId = UUID.randomUUID().toString();
                Session newSession = SessionsManager.get().addSession(roomId, sessionName, mode, numPlayers, gridWidth, gridHeight);

                if (numPlayers > 1)
                    SocketServer.get().emitSessionUpdate(newSession);

                JsonObject sessionJson = new JsonObject()
                        .put("roomId", roomId)
                        .put("sessionName", sessionName);
                rc.response()
                        .setStatusCode(200)
                        .putHeader("content-type",
                                "application/json; charset=utf-8")
                        .end(sessionJson.encode());
            } catch (Exception e) {
                rc.response()
                        .setStatusCode(400)
                        .putHeader("content-type",
                                "application/json; charset=utf-8")
                        .end();
            }
        });
    }

    @Override
    public void start() {
        vertx.createHttpServer()
                .requestHandler(router)
                .listen(port)
                .onSuccess(server ->
                        System.out.println(
                                "[HTTP Server] - HTTP server started on port " + server.actualPort()
                        )
                );
    }
}