stages:
  - build
  - test

build:
  image: gradle:6.9.3-jdk11-alpine
  stage: build
  script:
    - cd server-session
    - gradle build

test:
  image: gradle:6.9.3-jdk11-alpine
  stage: test
  needs: ["build"]
  script:
    - cd server-session
    - gradle check